icons_format = "{icon}"

[theme]
theme = "srcery"

[icons]
icons = "awesome6"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "

[[block]]
block = "cpu"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[ block ]]
block = "battery"
format = " $icon $percentage "
interval = 2

[[block]]
block = "time"
interval = 60
# format = "%a %d/%m %R"
