[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome6"

[[ block ]]
block = "net"
# format = " $icon ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
# format = "{ip} {speed_down;K*B} {speed_up;K*B}"
interval = 2

[[ block ]]
block = "memory"

[[ block ]]
block = "cpu"

# [[ block ]]
# block = "storage"


# [[ block ]]
# block = "battery"

[[block]]
block = "time"
interval = 60
# format = "%a %d/%m %R"
