[general]
out_dir = /home/deve/.cache/wal/
; backend = libimagequant
backend = cwal


[options]
alpha = 1.00
saturation = 0.20
contrast = 2.00
mode = dark
cols16_mode = darken

[random]
random_dir = ~/Pictures/Wallpapers/


[links]
sway = | swaymsg reload
nvim = | pkill -SIGUSR1 nvim
vibepanel = | pgrep -x "vibepanel" &>/dev/null && pkill -USR1 vibepanel || true && vibepanel &
