[colors]

[colors.bright]
black = "#555555"    # Dark gray (brighter black for contrast)
blue = "#5294e2"     # Adwaita blue (bright variant)
cyan = "#34e2e2"     # Adwaita cyan (bright)
green = "#8cc85f"    # Adwaita green (bright)
magenta = "#b48ead"  # Adwaita purple (bright)
red = "#e06262"      # Adwaita red (bright)
white = "#ffffff"    # Pure white for bright text
yellow = "#f0c674"   # Adwaita yellow (bright)

[colors.cursor]
cursor = "#d3d7cf"   # Light gray cursor (Adwaita neutral highlight)
text = "#2e3436"     # Dark text for cursor background

[colors.normal]
black = "#2e3436"    # Adwaita dark gray (standard black)
blue = "#3465a4"     # Adwaita blue
cyan = "#06989a"     # Adwaita cyan
green = "#4e9a06"    # Adwaita green
magenta = "#75507b"  # Adwaita purple
red = "#cc0000"      # Adwaita red
white = "#d3d7cf"    # Adwaita light gray (standard white)
yellow = "#c4a000"   # Adwaita yellow

[colors.primary]
background = "#2e3436"  # Adwaita dark background
foreground = "#eeeeec"  # Adwaita light foreground for text

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "Iosevka"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[window]
decorations = "full"
dynamic_title = true
opacity = 1

[window.padding]
x = 15
y = 10
