# Comigo设置文件(config.toml)，放在默认保存目录中。可选值：RAM（不保存）、HomeDir（$HOME/.config/comigo/config.toml）、NowDir（当前执行目录）、ProgramDir（程序所在目录）下。可用“comi --config-save”生成本文件
# 网页服务端口，此项配置不支持热重载
Port = 36613
# 自定义二维码显示的主机名
Host = '127.0.0.1'
# 默认扫描的书库文件夹
StoresPath = ['/home/deve/Downloads/']
# 扫描书籍的时候，需要排除的文件或文件夹的名字
ExcludePath = ['.comigo', '.idea', '.vscode', '.git', 'node_modules', 'flutter_ui', '$RECYCLE.BIN', 'System Volume Information', '.cache']
# 扫描压缩包时，用于统计图片数量的图片文件后缀
SupportMediaType = ['.jpg', '.jpeg', '.jpe', '.jpf', '.jfif', '.jfi', '.png', '.gif', '.apng', '.bmp', '.webp', '.ico', '.heic', '.heif', '.avif']
# 支持的书籍压缩包后缀
SupportFileType = ['.zip', '.tar', '.rar', '.cbr', '.cbz', '.epub', '.tar.gz', '.tgz', '.tar.bz2', '.tbz2', '.tar.xz', '.txz', '.tar.lz4', '.tlz4', '.tar.sz', '.tsz', '.bz2', '.gz', '.lz4', '.sz', '.xz', '.mp4', '.webm', '.pdf', '.m4v', '.flv', '.avi', '.mp3', '.wav', '.wma', '.ogg']
# 压缩包或文件夹内，至少有几张图片，才算作书籍
MinImageNum = 1
# 扫描文件时，超过几秒钟，就放弃扫描这个文件，避免卡在特殊文件上
TimeoutLimitForScan = 0
# 启用上传功能
EnableUpload = false
# 上传文件存储位置，默认在当前执行目录下创建 upload 文件夹
UploadPath = ''
# 最大扫描深度
MaxScanDepth = 3
# 非utf-8编码的ZIP文件，尝试用什么编码解析，默认GBK
ZipFileTextEncoding = 'gbk'
# 扫描完成后，打印所有可能的阅读链接二维码
PrintAllPossibleQRCode = false
# 开启Debug模式
Debug = false
# 是否同时打开浏览器，windows默认true，其他默认false
OpenBrowser = true
# 只在本机提供阅读服务，不对外共享，此项配置不支持热重载
DisableLAN = true
# 默认阅读模式，默认为空，可以设置为scroll或flip
DefaultMode = 'scroll'
# 是否启用登录。默认不需要登陆。此项配置不支持热重载。
EnableLogin = false
# 启用登陆后，登录界面需要的用户名。
Username = 'comigo'
# 启用登陆后，登录界面需要的密码。
Password = ''
# 启用登陆后，cookie过期的时间。单位为分钟。默认180分钟后过期。
Timeout = 65535
# 是否启用HTTPS协议。需要设置证书于key文件。
EnableTLS = false
# TLS/SSL 证书文件路径 (default:
CertFile = ''
# TLS/SSL key文件路径 (default:
KeyFile = ''
# 开启本地图片缓存，可以加快二次读取，但会占用硬盘空间
UseCache = true
# 本地图片缓存位置，默认系统临时文件夹
CachePath = '/tmp/comigo_cache'
# 退出程序的时候，清理web图片缓存
ClearCacheExit = true
# 启用本地数据库，保存扫描到的书籍数据。此项配置不支持热重载。
EnableDatabase = false
# 启用本地数据库时，扫描完成后，清除不存在的书籍。
ClearDatabaseWhenExit = true
# 是否保存程序Log到本地文件。默认不保存。
LogToFile = false
# Log文件的保存位置
LogFilePath = ''
# Log文件名
LogFileName = 'comigo.log'
# 生成书籍元数据
GenerateMetaData = false
