gui:
  authorColors: {}
  branchColors: {}
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  nerdFontsVersion: "3"
  skipDiscardChangeWarning: false
  skipStashWarning: false
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: flexible
  language: auto
  timeFormat: 02 Jan 06 15:04 IST
  commitLength:
  show: true
  skipNoStagedFilesWarning: false
  showListFooter: true
  showFileTree: true
  showRandomTip: true
  showCommandLog: true
  showBottomLine: true
  commandLogSize: 8
  splitDiff: auto
  theme:
    activeBorderColor:
      - '#94e2d5'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    searchingActiveBorderColor:
      - '#f9e2af'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    inactiveViewSelectedLineBgColor:
      - '#6c7086'
    cherryPickedCommitFgColor:
      - '#94e2d5'
    cherryPickedCommitBgColor:
      - '#45475a'
    markedBaseCommitFgColor:
      - '#89b4fa'
    markedBaseCommitBgColor:
      - '#f9e2af'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'

  showIcons: true
git:
  parseEmoji: true
customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
