include=~/.cache/cwal/colors-foot.ini

[main]
term=xterm-256color
#font=JetBrains Mono:size=8,Noto Color Emoji
font=Hack:size=8,Noto Color Emoji

#font-italic=Victor Mono:style=Italic

pad=12x12 center
# line-height=13
# alpha-mode=matching
# transparent-fullscreen=true
dpi-aware=true

[key-bindings]
clipboard-copy=Mod1+c
clipboard-paste=Mod1+v


[scrollback]
lines=5000

