#!/bin/bash
swaync-client -R -rs
sleep 1

notify-send -u critical "Test message: critical test 1"
notify-send -u normal "Test message: normal test 2"
notify-send -u low "Test message: low test 3"
# dunstify -A yes,ACCEPT -A no,DECLINE "Call waiting"
