#!/bin/bash
killall swaync

sleep 1
swaync &

sleep 1

swaync-client -R -rs

notify-send -u critical "Test message: critical test 1"
notify-send -u normal "Test message: normal test 2"
notify-send -u low "Test message: low test 3"
dunstify -A yes,ACCEPT -A no,DECLINE "Call waiting"
