[config]
# Menetapkan apakah akan mengatur wallpaper (set) dan menjalankan perintah (command)
set = true
# command = "swww"
# arguments = ["img", "--transition-type", "grow", "{{image}}"]

# Hooks untuk menyegarkan aplikasi setelah warna dihasilkan (misalnya, untuk Waybar di Hyprland)
# post_hook = "pkill waybar && waybar &"


[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'
