# Global Configs
[config]
version_check = false


[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.cache/wal/colors-rofi.rasi'

[templates.sway]
input_path = '~/.config/matugen/templates/sway.conf'
output_path = '~/.cache/wal/colors-sway'
post_hook   = 'swaymsg reload'

[templates.fish]
input_path = '~/.config/matugen/templates/colors.fish'
output_path = '~/.cache/wal/colors.fish'


[templates.css]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.cache/wal/colors.css'

#
# [templates.fuzzel]
# input_path = '~/.config/matugen/templates/fuzzel.ini'
# output_path = '~/.config/fuzzel/colors.ini'
#
#
# [templates.niri]
# input_path = '~/.config/matugen/templates/niri-colors.kdl'
# output_path = '~/.config/niri/colors.kdl'
#
[templates.foot]
input_path = '~/.config/matugen/templates/foot.ini'
output_path = '~/.cache/wal/colors-foot.ini'
post_hook   = '''

'''

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/post-hook-scripts/gtk-theme-reload.sh'

# ...

[templates.neovim]
input_path = "~/.config/matugen/templates/nvim.json"
output_path = "~/.cache/wal/colors-nvim.json"
post_hook = "pkill -SIGUSR1 nvim"
