[config.wallpaper]
set = true
# command = "swaybg"
# arguments = ["-i", "{{image}}", "-m", "fill"]
command = "awww"
arguments = ["img", "--transition-type", "center"]

# Hooks untuk menyegarkan aplikasi setelah warna dihasilkan (misalnya, untuk Waybar di Hyprland)
# post_hook = "pkill waybar && waybar &"


[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'


[templates.niri]
input_path = './templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'

[templates.foot]
input_path = './templates/foot-colors.ini'
output_path = '~/.config/foot/colors.ini'
post_hook   = '''
  touch "$HOME/.config/foot/foot.ini" || :
'''
