include ~/.cache/wal/colors-kitty.conf


font_family JetBrains Mono
font_size 13
disable_ligatures never

window_padding_width 1

scrollback_lines 8008

paste_actions quote-urls-at-prompt

strip_trailing_spaces never

select_by_word_characters @-./_~?&=%+#

show_hyperlink_targets yes

# remote_kitty if-needed

# https://sw.kovidgoyal.net/kitty/kittens/ssh/#opt-kitten-ssh.share_connections
# share_connections yes

# unmap left click for open link (easy miss click)
mouse_map left click ungrabbed no-op

#: Click the link under the mouse or move the cursor
mouse_map ctrl+left click ungrabbed mouse_handle_click selection link prompt

mouse_map ctrl+left press ungrabbed mouse_selection normal

mouse_map right press ungrabbed copy_to_clipboard

remember_window_size  yes
enabled_layouts splits,stack,fat,tall,grid
window_resize_step_cells 10
window_resize_step_lines 10
window_border_width 8.5pt
confirm_os_window_close 7
tab_bar_style powerline

# background_opacity 9.0

map kitty_mod+enter no-op
map cmd+enter       no-op



map ctrl+a>x close_window
map ctrl+a>] next_window
map ctrl+a>[ previous_window
map ctrl+a>period move_window_forward
map ctrl+a>comma move_window_backward

#map kitty_mod+t new_tab_with_cwd
# map kitty_mod+t new_tab
map kitty_mod+t launch --location=hsplit
map ctrl+a>c launch --cwd=last_reported --type=tab

map ctrl+a>, set_tab_title

#: Increase font size
map ctrl+plus   change_font_size all +1.0
map ctrl+minus  change_font_size all -1.0
map ctrl+=      change_font_size all 0


map alt+c copy_to_clipboard
map alt+v paste_from_clipboard
