#!/bin/bash

$i=1
while [ 1 ]; do
    if [[ $2 == "xdotool" ]]
    then
        xdotool click 1
    else
        doas ydotool click 1
    fi

    notify-send 'click '$i -t 100
    let "i+=1"
    sleep $1
done

