#!/bin/bash

if ! pkill -INT -P "$(pgrep -xo auto-click)" xdotool 2>/dev/null; then
    pkill -USR1 -x auto-clickd
    notify-send "Start auto click"

    while [ 1 ]; do
        xdotool click 1
    done

    pkill -USR2 -x auto-clickd
else
  notify-send "Stop auto click"
fi
