#!/usr/bin/env fish

if test (gsettings get org.gnome.desktop.interface color-scheme) = "'prefer-light'"
    # dark side
    # ---------------------------------------
    echo 'dark' > ~/.local/share/colorscheme
    # darkman set dark
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark
    gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
    ln -sf ~/.local/share/nwg-look/dark ~/.local/share/nwg-look/gsettings

    cwal --mode dark --random "~/Pictures/Wallpapers/"
    notify-send "  Theme" "Current theme is Dark"
else
    # light side
    # ---------------------------------------
    echo 'light' > ~/.local/share/colorscheme
    # darkman set light
    gsettings set org.gnome.desktop.interface color-scheme prefer-light
    gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'
    ln -sf ~/.config/alacritty/alacritty-light.yml ~/.config/alacritty/alacritty.yml
    ln -sf ~/.local/share/nwg-look/light ~/.local/share/nwg-look/gsettings

    cwal --mode light --random "~/Pictures/Wallpapers/"
    notify-send "  Theme" "Current theme is light"
end


# nwg-look -a
swaymsg reload
