#!/usr/bin/env fish

# Configuration
set WALLPAPER_DIR "$HOME/Pictures/Wallpapers"
set WAL_POST "$HOME/.config/wal/post.sh"

# Pick a random wallpaper for tools that require a specific file path
set -l RANDOM_WALLP (find "$WALLPAPER_DIR" -type f | shuf -n 1)

# Detect System Theme (Dark/Light)
set -l mode (gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null)

if type -q matugen
    echo "Applying theme with Matugen using: $RANDOM_WALLP"
    if test "$mode" = "'prefer-dark'"
        matugen image "$RANDOM_WALLP" -m dark
    else
        matugen image "$RANDOM_WALLP" -m light
    end

else if type -q wal
    echo "Applying theme with Pywal..."
    if test "$mode" = "'prefer-dark'"
        wal -i "$WALLPAPER_DIR" -o "$WAL_POST"
    else
        wal -l -i "$WALLPAPER_DIR" -o "$WAL_POST"
    end

else if type -q cwal
    echo "Applying theme with Pywal..."
    if test "$mode" = "'prefer-dark'"
        cwal -r --mode dark
    else
        cwal -r --mode light
    end

else
    notify-send "No wallpaper application found"
    exit 1
end
