#!/bin/bash
if ! pkill -INT -P "$(pgrep -xo record-screen)" wf-recorder 2>/dev/null; then
    geometry="$(slurp -d)"
    if [ -n "$geometry" ]; then
        pkill -USR1 -x record-screend
        mkdir -p ~/Videos/Recordings
        notify-send "  Recording"

        file=~/Videos/Recordings/"screen-record-$(date +%Y-%m-%d-%H-%M-%S).mp4"
        # wf-recorder -f $file -g "$geometry"
        #
        wf-recorder -f $file -g "$geometry" --force-yuv
        # wl-screenrec -f $file -g "$geometry"

        gdrive_file=/tmp/record_to_gdrive.txt
        gdrive files upload --parent 1x8koRfNslb509g1sm9p8i-JlM2WUIyCr $file > $gdrive_file
        cat $gdrive_file | grep ViewUrl | sed 's/ViewUrl: //g' | wl-copy

        # rm $file
        notify-send "  Stop Recording"
        pkill -USR2 -x record-screend
    fi
fi
