#!/usr/bin/env sh

if [ -e ~/.profile ]
then
    source ~/.profile
fi

export QT_QPA_PLATFORM=wayland
# export QT_STYLE_OVERRIDE=kvantum
export QT_QPA_PLATFORMTHEME=gtk2

export MOZ_ENABLE_WAYLAND=1
# export QT_STYLE_OVERRIDE=adwaita
export XDG_SESSION_TYPE=wayland
export CLUTTER_BACKEND=wayland
export BEMENU_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway

# export GDK_CORE_DEVICE_EVENTS=1
export NO_AT_BRIDGE=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"

export SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
exec dbus-run-session Hyprland

