#!/usr/bin/env sh

if [ -e ~/.profile ]
then
    source ~/.profile
fi

export MOZ_ENABLE_WAYLAND=1
# export QT_QPA_PLATFORM=qt5ct

export QT_STYLE_OVERRIDE=kvantum
# export QT_STYLE_OVERRIDE=adwaita
export XDG_SESSION_TYPE=wayland
export CLUTTER_BACKEND=wayland
export BEMENU_BACKEND=wayland

export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway

# export GDK_CORE_DEVICE_EVENTS=1
export NO_AT_BRIDGE=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"

export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"


exec /usr/bin/sway
