#!/usr/bin/env sh


if [ -e ~/.profile ]
then
    source ~/.profile
fi

if [ -e ~/.private-env ]
then
    source ~/.private-env
fi


export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
# export QT_STYLE_OVERRIDE=adwaita
export XDG_SESSION_TYPE=wayland
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export XDG_CURRENT_DESKTOP=qtile

# export GDK_CORE_DEVICE_EVENTS=1
export NO_AT_BRIDGE=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"

exec dbus-run-session qtile start -b wayland
