#!/usr/bin/env sh

if [ -e ~/.profile ]
then
    source ~/.profile
fi

if [ -e ~/.private-env ]
then
    source ~/.private-env
fi



export QT_QPA_PLATFORM=wayland
# export QT_STYLE_OVERRIDE=kvantum
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"


export MOZ_ENABLE_WAYLAND=1
# export QT_STYLE_OVERRIDE=adwaita
export XDG_SESSION_TYPE=wayland
export CLUTTER_BACKEND=wayland
export BEMENU_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway

export GDK_BACKEND=wayland
# export GDK_CORE_DEVICE_EVENTS=1
export NO_AT_BRIDGE=1
export SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
export TERMINAL=/usr/bin/foot


config=~/.config/sway/nox11-config
if [[ $1 == *"x11"* ]];
then
    config=~/.config/sway/config
fi

exec /usr/bin/sway --config $config
# exec dbus-run-session /usr/bin/sway --config $config
