#!/usr/bin/env fish

notify-send "PicGo Prepare Upload" "Mohon tunggu..."

# Menggunakan set untuk variabel dan string match untuk mencari URL
set URL (picgo u --debug | string match -r 'https://\S+')

if test -n "$URL"
    echo "$URL" | wl-copy
    notify-send "PicGo Upload Success" "$URL"
else
    notify-send "PicGo Upload Failed" "Gagal mendapatkan URL. Periksa konfigurasi PicGo."
end
